# Personal tips that helped Carlos in moving from Matlab to Jupyter and Python -- in progress

These are personal tips based on personal preferences that Carlos Brody encountered in the Summer and Fall of 2016 as he moved from Matlab to Jupyter/Python -- others might like things differently!

<h1 id="tocheading">Making a table of contents</h1>
<div id="toc"></div>


In [ ]:
%%javascript
$.getScript('https://sites.google.com/site/brodylabhome/files/make_table_of_contents.js')


# 1) Having static figure windows outside the browser

I like figure windows that don't scroll away every time I run some code.

The way to do that is to ask `matplotlib`, from the outset of the session, to use `qt` as its back end:

In [ ]:
%matplotlib qt

from matplotlib import pyplot as plt

And then we can place figures where we want them on the screen and they stay there.

In [ ]:
def create_and_place_figure(x=1270, y=50, width=640, height=550, fignum=None):
    """
    Creates and places a figure at the indicated x, y, width, and height, in pixels, counted
    from the top left of the screen.
    
    PARAMETERS:
    
        x=1270     top left position of figure, in pixels    
        y=50       top left position of figure, in pixels
        width=640  width of figure, in pixels
        height=550 height of figure, in pixels

        fignum=None    If not passed, a new figure is created. If passed, it should be a figure object,
                   and then a new figure will not be created but instead the passed figure will be resized
                   and repositioned
               
    RETURNS:
    
        fig    The figure object affected.
    """
    if fignum==None:
        fig = plt.figure()
    else:
        fig = plt.figure(fignum)

    manager = plt.get_current_fig_manager()
    wpos = list(manager.window.geometry().getRect())
    wpos[0] = x
    wpos[1] = y
    wpos[2] = width
    wpos[3] = height
    
    manager.window.setGeometry(wpos[0], wpos[1], wpos[2], wpos[3])
    manager.window.raise_()
    
    fig.canvas.draw()
    fig.canvas.flush_events()
    return fig




# 2) One-dimensional matrices

If you take a slice of a 2-d matrix, surprisingly (to a Matlab refugee), you don't get back a matrix with only one column or only one vector: you get back a 1-d matrix, (which is neither a row nor a column vector), so if you multiply a amtrix times it, you don't get the expected row vector back:

In [13]:
import numpy as np

A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print("A = \n", A)

b = A[2,:].T
print("shape(b) = ", np.shape(b), "\nb = \n", b)

print("shape(A@b) = ", np.shape(A@b))

A = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape(b) =  (3,) 
b = 
 [7 8 9]
shape(A@b) =  (4,)


If you really wanted b to be a row vector, you can reshape it, but that's tedious.

The other approach, if you really want a 2-d slice (with a single row or column) is to specify both the starting and ending indices in the slice:

In [14]:
b = A[2:3,:].T
print("shape(b) = ", np.shape(b), "\nb = \n", b)

print("shape(A@b) = ", np.shape(A@b))


shape(b) =  (3, 1) 
b = 
 [[7]
 [8]
 [9]]
shape(A@b) =  (4, 1)


# 3) Default arguments, their initialization, and kwarg dictionaries

# 4) Variables passed by reference

# 5) inheriting the caller's namespace